import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-highest": "#e4e4cc",
        "surface-tint": "#745853",
        "surface-variant": "#e4e4cc",
        "primary-container": "#5b413c",
        "surface-bright": "#fbfbe2",
        "on-surface": "#1b1d0e",
        "inverse-surface": "#303221",
        "tertiary-fixed": "#ffdbd1",
        "outline-variant": "#d4c3be",
        "on-tertiary-fixed": "#3b0800",
        "secondary-fixed-dim": "#e4beb2",
        "on-primary-fixed": "#2b1613",
        "inverse-primary": "#e3beb8",
        "on-secondary-fixed-variant": "#5b4137",
        "on-primary-fixed-variant": "#5b403c",
        "surface-dim": "#dbdcc3",
        "background": "#fbfbe2",
        "on-error-container": "#93000a",
        "outline": "#827470",
        "secondary": "#75584d",
        "surface": "#fbfbe2",
        "tertiary": "#601300",
        "on-surface-variant": "#504441",
        "on-tertiary-fixed-variant": "#881f00",
        "surface-container-high": "#eaead1",
        "tertiary-container": "#881f00",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdbce",
        "on-secondary-container": "#795c51",
        "surface-container": "#efefd7",
        "tertiary-fixed-dim": "#ffb5a1",
        "on-tertiary-container": "#ff9a7f",
        "inverse-on-surface": "#f2f2d9",
        "on-secondary-fixed": "#2b160f",
        "primary-fixed-dim": "#e3beb8",
        "on-primary-container": "#d1ada7",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-background": "#1b1d0e",
        "primary-fixed": "#ffdad4",
        "surface-container-low": "#f5f5dc",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fed7ca",
        "primary": "#422b27",
      },
      fontFamily: {
        headline: ["Noto Serif KR", "serif"],
        body: ["Noto Serif KR", "serif"],
        label: ["Public Sans", "sans-serif"],
        serif: ["Noto Serif KR", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}

export default config
